spring:
  application:
    name: task-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tasks-db
    username: root
    password: P@ss2021
  jpa:
    format-sql: true
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#server:
#  port: 8083
#below property will make sure to allocate available port dynamically on run time if the service has multiple running instance
server:
  port: 0
#Eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#below property will generate a random name for each instance of this service and than register to the Discovery service
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}